### ISSUE TITLE
Why this uses an old rust-ffmpeg-sys?

### ISSUE THREAD

**Issue by lucaszanella** [meh/rust-ffmpeg#135]
Tried to build this with my local rust-ffmpeg-sys instead of the one in crates and found out that the one used by this repo is old. Why? 

I tried simply pointing to the newest one but I get compilation errors. Can I upgrade myself or there is a reason it points to the old one?

**Comment by ptree44** [comment]
I believe this repo is dead and you should use ffmpeg-next which is a fork

**Comment by barzamin** [comment]
there was a decent period of inactivity that broke a bunch of stuff; ffmpeg-sys also didn't get crate releases for like... a year or more? which kinda killed off this repo because things were blocked on that

i think meh is working on bringing it up to a more recent version but afaik it's not high-priority for them, so probably just use -next haha

**Comment by meh** [comment]
Hey now, I did release a new ffmpeg-sys version a month or so ago! :P

I'll bring this back up to date as well very very soon, I'm starting to use it again.
